# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: ado-extension-demo

trigger: none

variables:
  - name: resource_group
    value: kritifaujdar-rg
  - name: subscription
    value: ea4faa5b-5e44-4236-91f6-5483d5b17d14
  - name: workspace
    value: kritifaujdar-ws
  - name: azure_service_connection
    value: 'kritifaujdar-ws-level'

jobs:
- job: SubmitAMLJob
  displayName: Submit AML Job
  timeoutInMinutes: 300
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: none
  - task: UsePythonVersion@0
    displayName: Use Python >=3.8
    inputs:
      versionSpec: '>=3.8'

  - bash: |
      set -ex

      az version
      az extension add -n ml
    displayName: 'Add AML Extension'

  - task: AzureCLI@2
    name: submit_aml_job_task
    displayName: Submit AML Job Task
    inputs:
      azureSubscription: 'kritifaujdar-ws-level'
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
      
        # Create temp component yaml
        touch component.yml
        printf "\$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json\ncommand: sleep 2m\ncompute: cpu-cluster\nenvironment:\n  image: library/python:latest\n" > component.yml
        cat component.yml

        # submit component job and get the run name
        job_out=$(az ml job create --file component.yml -g $(resource_group) -w $(workspace) --query name)

        # Remove quotes around run name
        run_name=$(sed -e 's/^"//' -e 's/"$//' <<<"$job_out")
        echo $run_name

        # Set output variable for next task
        echo "##vso[task.setvariable variable=RUN_NAME;isOutput=true;]$run_name"

- job: WaitForCallback
  pool: server
  timeoutInMinutes: 0
  dependsOn: SubmitAMLJob
  variables: 
    run_name_from_submit_job: $[ dependencies.SubmitAMLJob.outputs['submit_aml_job_task.RUN_NAME'] ] 
  steps:
  - task: AMLJobWaitTask@0
    inputs:
      azureSubscription: 'kritifaujdar-ws-level'
      runName: $(run_name_from_submit_job)
